### ISSUE TITLE
Allow async loading

### ISSUE THREAD

**Issue by grapoza** [grapoza/vue-tree#13]

**Comment by grapoza** [comment]
This should include emitting `treeViewNodeLoad`

**Comment by grapoza** [comment]
@Lakshamana There are a few things I'm thinking through, but the rough idea (for now) would be to supply an async function responsible for loading child nodes as part of the tree node data for each node. For most real world uses I'd actually expect this to be populated once through the `modelDefaults` property of the tree, unless node-specific async loading was needed for some reason.

As for async loading, loading data from the server is a pretty likely case and the one that I've seen the most interest in so far.

Some thought needs to go into what indicates a load needs to happen. Some other implementations I've looked into seem to use one of two strategies:
1. Allow both the async function and some default set of children to be specified on the node, and the children loaded by the async function just get appended to the children array. There is a boolean in the node data that indicates whether the async load has been triggered before or not.
2. If the array of children is `null` that means we need to run the async function to load the children, which will populate the array.

And, while I'm dumping stuff out of my brain, this also needs to take into account how the `expanded` state interacts here. Any node that's expandable and with async loading needs to show the expander button as collapsed before the async load has happened, since that would act as the trigger for the load.

So yeah, still a few things that need to get thought out here. I'm hoping to have time sooner rather than later, as I'll want this async loading available for another project.

**Comment by Lakshamana** [comment]
@grapoza is there any contribution rule or guidelines (like: creating a feature branch or forking, testing, coding style, etc)? I can take this issue on if you want.

**Comment by grapoza** [comment]
You'd be the first to contribute on this repo, which is why there's no CONTRIBUTING.md. I'll go ahead a whip one of those up soon. For now, fork the repo and do you work there, and when you're done create a PR into this repo's master branch. Thanks for offering!

As far as guidelines, just use the [Vue Style Guide](https://vuejs.org/v2/style-guide/) and otherwise do your best to stick to the styles and conventions that're already used. There's an `editorconfig` to help with the basic stuff. When writing tests I've stuck with the `describe('when...` with nested `describe('and...` for scoping and `it('should...` for test descriptions. Documentation is generated with pandoc from sources under `docsrc`. I'm purposefully not giving you a ton of information here so you can come back to me with questions and help me fill in the gaps I'll inevitably need to fill in with the CONTRIBUTING.md.

**Comment by Lakshamana** [comment]
nice! :+1:
