### ISSUE TITLE
Loading initial-model from mounted

### ISSUE THREAD

**Issue by robbaker292** [grapoza/vue-tree#192]
Version 2.1.4

I am looking to have a tree where the initial data is loaded through vue's mounted (or, loaded async another way). When I set my a data parameter of `areaData` to be null or empty array, and an axios function to mount that data, the tree does not render.

My current workaround is to create a root node, that async loads the data (but then the child nodes need a different async loading function - I have only two levels).

Is there a way of setting the initial data for the tree to be either mounted, or loaded async in another way?

Many thanks

**Comment by grapoza** [comment]
One thing I've done is to pass an empty array to the tree as the initial model, then push asynchronously loaded data to that array once it's fetched (with that fetch occurring outside the treeview). That sets up the root level nodes. I use the `modelDefaults` to set up the async loading function to later get the data for the child nodes. I'll put a sample on this comment, it may be clearer than my description.

I assume what you're actually looking for is a way to specify the async loading method in the setup of the tree itself. That's something I could add into the 3.0.0 version I'm finishing up now if you'd like, and if so just let me know if there are any specific requirements you'd like me to keep in mind. It'll probably get released next weekend, depending on how much time my daughter has already scheduled out for me being a horsey. The fact that this comment has taken me two hours to write does not bode well...

```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>No Initial Root Node</title>
  <script src="https://unpkg.com/vue"></script>
  <script src="../../dist/vue-tree.umd.js"></script>
  <link rel="stylesheet" href="demo.css">
  <link rel="stylesheet" href="../../dist/vue-tree.css">
</head>

<body>
  <div class="container">
    <h1>No Initial Root Node</h1>
    <div id="app">
      <tree id="customtree" :initial-model="model" :model-defaults="modelDefaults" ref="tree"></tree>
      <button @click="addInitialNode">Add Root Node</button>
    </div>
  </div>

  <script type='module'>

    new Vue({
      components: {
        tree: window['vue-tree']
      },
      data() {
        return {
          childCounter: 0,
          model: [],
          modelDefaults: {
            loadChildrenAsync: this.loadChildrenCallback,
            deletable: true
          }
        };
      },
      methods: {
        loadChildrenCallback(parentModel) {
          this.childCounter++;
          let currentCounter = this.childCounter;
          return new Promise(resolve => setTimeout(resolve.bind(null, [{ id: `child-node${currentCounter}`, label: `Child ${currentCounter}` }]), 1000));
        },
        addInitialNode() {
          if (this.model.length === 0) {
            this.model.push(
              {
                id: 'rootNode',
                label: 'Root Node',
                treeNodeSpec: {
                  deletable: false
                }
              });
          }
        }
      }
    }).$mount('#app');
  </script>
</body>

</html>
```

**Comment by robbaker292** [comment]
> One thing I've done is to pass an empty array to the tree as the initial model, then push asynchronously loaded data to that array once it's fetched (with that fetch occurring outside the treeview). That sets up the root level nodes. I use the `modelDefaults` to set up the async loading function to later get the data for the child nodes. I'll put a sample on this comment, it may be clearer than my description.
> 
> I assume what you're actually looking for is a way to specify the async loading method in the setup of the tree itself.

Not quite - what I'm looking for is a way to asynchronously load the root node. However, the example you've given has helped greatly, and this is my current, working, example:

```js
<template>
  <div>
    <tree-view
      id="areas-tree"
      :initial-model="model"
      :model-defaults="modelDefaults"
      selection-mode="multiple"
    ></tree-view>
  </div>
</template>

<script>
import axios from 'axios';
import TreeView from '@grapoza/vue-tree';

export default {
  components: {
    TreeView,
  },
  data() {
    return {
      model: [],
      areaTypes: [],
      modelDefaults: {
        selectable: true,
        labelProperty: 'name',
        input: {
          type: 'checkbox',
        },
      },
    };
  },
  methods: {
    async loadAreas(p) {
      let result = [];
      await axios
        .get(`${process.env.VUE_APP_APIURL}areaofinterest?includeAreas=false&typeId=${p.id}`)
        .then((response) => {
          result = response.data;
        });
      return result;
    },
    addInitialNode() {
      if (this.model.length === 0) {
        this.model.push(this.areaTypes[0]);
      }
    },
  },
  mounted() {
    axios
      .get(`${process.env.VUE_APP_APIURL}areatypes`)
      .then((response) => {
        this.areaTypes = response.data.map((e) => {
          e.treeNodeSpec = {
            expandable: true,
            loadChildrenAsync: this.loadAreas,
          };
          return e;
        });
        this.addInitialNode();
      });
  },
};
</script>

```

This has successfully avoided having a "dummy" root node that's always fixed - now the root nodes are added asynchronously.

However, if there was an option to specify a function to load the initial data, this would avoid this workaround. Once again, many thanks for the help, such a quick response, and a great component!

**Comment by grapoza** [comment]
Sounds like we're on the same page with what you want, though I phrased it rather poorly. I've been giving this some thought and this makes a lot of sense to me, so I'll add an issue to the 3.0.0 release to allow you to specify a function the treeview should use to load the initial model.

As a side note, you can also use `splice` to add multiple items to the array at once and have Vue pick them up and make them reactive. That's what I'm doing with the [asynchronously loaded children](https://github.com/grapoza/vue-tree/blob/6dcfa2cb1131ef6cdfddd58f9c77c421de218521/src/components/TreeViewNode.vue#L598) and with a bunch of the drag and drop operations.

**Comment by grapoza** [comment]
Closing out this question and implementing enhancement #194.

**Comment by grapoza** [comment]
@robbaker292 If you get some time in the near future would you mind taking a look at https://github.com/grapoza/vue-tree/pull/196?
