### ISSUE TITLE
Officially drop IE11

### ISSUE THREAD

**Issue by grapoza** [grapoza/vue-tree#208]
The current browserslist in the package.json only specifies the default browser set, which includes IE11. By the time this component reaches version 4.0.0 development, hopefully IE11 will have so little market share that it will have been removed from the defaults. If not, it will just get dropped explicitly as there's not a compelling reason to continue acknowledging that god awful abortion of a browser.

A quick test run of just adding `"not IE 11"` to the browserslist resulted in a 50% decrease in the size of the component.

**Comment by jimmywarting** [comment]
Most tech companies (LinkedIn, Zendesk, Microsoft 365, etc) has already dropped support for IE11.

Microsoft themselves will drop support in August (https://www.theverge.com/2020/8/17/21372487/microsoft-internet-explorer-11-support-end-365-legacy-edge).

https://death-to-ie11.com/

**Comment by grapoza** [comment]
Before:

```  dist\vue-tree.umd.min.js    90.05 KiB                                                                  28.01 KiB
  dist\vue-tree.umd.js        274.58 KiB                                                                 62.94 KiB
  dist\vue-tree.common.js     274.20 KiB                                                                 62.82 KiB
  dist\vue-tree.css           2.61 KiB                                                                   0.51 KiB
```

After:
```  dist\vue-tree.umd.min.js    47.13 KiB                                                                  13.12 KiB
  dist\vue-tree.umd.js        130.83 KiB                                                                 29.29 KiB
  dist\vue-tree.common.js     130.45 KiB                                                                 29.17 KiB
  dist\vue-tree.css           2.61 KiB                                                                   0.51 KiB
```
