### ISSUE TITLE
Drag and Drop touchscreen not works

### ISSUE THREAD

**Issue by AlbertoTorrisi** [grapoza/vue-tree#216]
Hello everyone, 
I have a problem when i try to use with touchscreen the drag and drop system. With mouse it work perfectly.

1. Install by Yarn
2. import component in my page of my Vue Project
3. use the component in mobile mode
4. drag and drop in mobile mode not work

Do you have some suggestions for fix this bug? thank you

**Comment by grapoza** [comment]
@AlbertoTorrisi I've looked into a few different options for this, and until there's some native touch drag handling available the best approach I've found is to add a polyfill to map touch events to drag and drop events. The one I played around with is https://github.com/Bernardo-Castilho/dragdroptouch which I added to a test page and it was able to handle the tree's functionality pretty well without any modifications. I'll add the caveat that I've only tested it in desktop browsers with developer tools emulating a touch device, so results across different target devices may vary.

I'm going to keep an eye out for any changes to support for touch drag events, and if/when there's native support that works across target environments I'll add an enhancement to get that added.
