### ISSUE TITLE
Support for Vue 3?

### ISSUE THREAD

**Issue by TheAustinG** [grapoza/vue-tree#217]
I'm curious if you have any plans to update this to support Vue 3? There are very few Vue tree components out there and this one seems like a great fit for our project. But unfortunately, it does not appear to support Vue 3.

**Comment by grapoza** [comment]
The short answer is yes, Vue 3 is definitely something I want to support. It's one of those things that I've been meaning to get to for a while, but other things keep coming up. I'll add an enhancement issue to the 4.0.0 project, which I intended to add this support into anyway but hadn't documented yet. I'll work it along with things like #208 which I'll have to knock down at the same time.

For a timeline, I'm honestly not sure when I'd end up getting through the 4.0.0 tasks. If it gets to be too much to do in a reasonable amount of time I'll consider splitting some things out to a 4.x or 5.0.0. Having someone ask for something specifically is a great motivator, so I'll try to accelerate this a bit. Any specific requirement for your project?

**Comment by grapoza** [comment]
#218 is the new enhancement.

**Comment by grapoza** [comment]
@TheAustinG I managed to get this updated to use Vue 3, and the latest is now in master. I haven't published a beta package (I tend not to for smaller projects unless there's some great need for it) but if you want to try it out you can clone it and build it. If you do feel the need for a published beta package to try then let me know and I'll be happy to put one out.

**Comment by TheAustinG** [comment]
@grapoza Thank you so much for updating this! Sorry, I never got back to you on your first response, I have been absent the past couple of weeks. 

No need to publish the package, I can download and build it myself. Thanks again for your dedication to this!

**Comment by swana1337** [comment]
hello, when will the support for vue 3 will be released ? :)

kind regards

**Comment by grapoza** [comment]
@swana1337 I'm hoping it will be in the next couple of weeks. I just need to find time to work through the last two stories in the 4.0.0 project. Having said that, since it's likely neither the treegrid nor the full RTL support stories would break existing apps I could always release those as 4.1.0 later if they end up taking longer than is tolerable.

**Comment by grapoza** [comment]
@TheAustinG @swana1337 I released 4.0.0 yesterday, which contains the Vue 3 support. I'll close this issue, but I'm keeping an eye out for anything coming in against Vue 3 and vue-tree 4.0.0. Thanks for giving me the kick I needed to actually go ahead and get this in.
