### ISSUE TITLE
Tree does not render after upgrade to 4.0.0

### ISSUE THREAD

**Issue by dandee** [grapoza/vue-tree#227]
**Describe the bug**
Tree no longer renders after upgrade to version 4.0.0. Web browser console shows following error:

`[Vue warn]: Error in render: "TypeError: this.tns is undefined"`

**To Reproduce**
Upgrade to 4.0.0. Rebuild app. Run.

Code:

```
<tree-view id='tree' :load-nodes-async='loadTree' :model-defaults='treeDefaults' :selectionMode='"single"'>
  <template v-slot:loading-root>
    <div class='d-flex justify-content-center'>
      <div class='spinner-border text-primary' role='status'>
        <span class='sr-only'>Loading</span>
      </div>
    </div>
  </template>
</tree-view>
```

**Expected behavior**
Tree renders as before the upgrade.

**Additional context**
I think the bug is in src/mixins/NodeDataNormalizer.js@15:

```
      if (!this.tns) {
        this.model.treeNodeSpec = {};
      }
```

shouldn't it be like this?

```
      if (!this.tns) {
        this.tns = {};
      }
```

**Comment by grapoza** [comment]
Alright, I finally got a chance to take a look. So the 4.x+ vue-tree [only supports Vue 3+](https://grapoza.github.io/vue-tree/4.0.0/) at this point. I checked out the repro in case I could at least work around some issues, but I'm using some of the syntax/changes that aren't compatible even with the Vue 2 composition API package. I'm 99% sure that's what we're up against here.

Having said that, 4.0.0 is functionally equivalent to 3.0.3 except that it's updated a bit for minor development cleanup and to move everything to Vue 3. I'm planning on keeping up on security updates for vue-tree 3.x, and if you have anything you want or need from the component I'll be happy to look into getting it into both versions. I assume you primarily updated to 4.0.0 just to get the latest version?

PS: Thanks for the kind words! I probably went through all the same components you did before I wrote this, and there are a lot of components that are either A) really good but really expensive, or B) only able to do a subset of what I wanted, or C) had no accessibility. I'm very happy to see people actually find this useful.

**Comment by dandee** [comment]
All right, I see your point. I've got really fresh project starting up and tried to keep all dependencies up to date. I can easily downgrade back to 3.0.3 which I did but I still receive peculiar error/warning in the console (which I though would go away when I upgrade.) I'm going to issue separate bug report for that against version 3.0.3. Thank you for your time!
