### ISSUE TITLE
Single selection mode does not work with customised id property name

### ISSUE THREAD

**Issue by luckyrat** [grapoza/vue-tree#297]
Here: https://github.com/grapoza/vue-tree/blob/master/src/composables/selection/treeViewSelection.js#L105

The comparison is hardcoded to use the "id" property rather than the one that was configured to be used instead. Thus, the "old" selection is never removed.

**Comment by grapoza** [comment]
D'oh. I'll get that fixed this weekend.

**Comment by grapoza** [comment]
@luckyrat I've published 5.1.0, which contains this fix among some other change that were ready to go.

**Comment by luckyrat** [comment]
Thanks for the quick fix. I can confirm I've tested 5.1.0 and it's working now with my custom id property.
